version: "3"

services:
  hazelcast-node-1:
    image: hazelcast/hazelcast:latest
    restart: unless-stopped
    environment:
      HZ_NETWORK_JOIN: hazelcast-node-2,hazelcast-node-3
      JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    volumes:
      - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
    ports:
      - "${HAZELCAST_NODE_PORT_1}:5701"
    networks:
      - hazelcast-lecture

  hazelcast-node-2:
    image: hazelcast/hazelcast:latest
    restart: unless-stopped
    environment:
      HZ_NETWORK_JOIN: hazelcast-node-1,hazelcast-node-3
      JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    volumes:
      - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
    ports:
      - "${HAZELCAST_NODE_PORT_2}:5701"
    networks:
      - hazelcast-lecture

  hazelcast-node-3:
    image: hazelcast/hazelcast:latest
    restart: unless-stopped
    environment:
      HZ_NETWORK_JOIN: hazelcast-node-1,hazelcast-node-2
      JAVA_OPTS: -Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    volumes:
      - "./hazeclast.xml:/opt/hazelcast/config/hazelcast.xml"
    ports:
      - "${HAZELCAST_NODE_PORT_3}:5701"
    networks:
      - hazelcast-lecture
    
  api-loggin-1:
    build: 
      context: .
      dockerfile: loggin.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${LOGGIN_PORT_1}
    ports:
      - "${LOGGIN_PORT_1}:${LOGGIN_PORT_1}"
    networks:
      - hazelcast-lecture

  api-loggin-2:
    build: 
      context: .
      dockerfile: loggin.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${LOGGIN_PORT_2}
    ports:
      - "${LOGGIN_PORT_2}:${LOGGIN_PORT_2}"
    networks:
      - hazelcast-lecture

  api-loggin-3:
    build: 
      context: .
      dockerfile: loggin.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${LOGGIN_PORT_3}
    ports:
      - "${LOGGIN_PORT_3}:${LOGGIN_PORT_3}"
    networks:
      - hazelcast-lecture

  api-facade:
    build: 
      context: .
      dockerfile: facade.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${FACADE_PORT}
      PORT_MESSAGE: ${MESSAGE_PORT}
      PORT_LOGGER_1: ${LOGGIN_PORT_1}
      PORT_LOGGER_2: ${LOGGIN_PORT_2}
      PORT_LOGGER_3: ${LOGGIN_PORT_3}
    ports:
      - "${FACADE_PORT}:${FACADE_PORT}"
    networks:
      - hazelcast-lecture

  api-message:
    build: 
      context: .
      dockerfile: message.Dockerfile
    restart: unless-stopped
    environment:
      PORT_SEVICE: ${MESSAGE_PORT}
    ports:
      - "${MESSAGE_PORT}:${MESSAGE_PORT}"
    networks:
      - hazelcast-lecture

  hazelcast-management-center:
    image: hazelcast/management-center:latest
    restart: unless-stopped
    environment:
      - HZ_MAN_CENTER_CLUSTER_MEMBERS=hazelcast-node-1:5701,hazelcast-node-2:5701,hazelcast-node-3:5701
    ports:
      - "8080:8080"
    networks:
      - hazelcast-lecture

networks:
  hazelcast-lecture:
    driver: bridge
